/**
 * Applies calculated X/Y coordinates to the active microflow or nanoflow.
 *
 * Microflows and nanoflows share the same structure (objectCollection + flows), so the
 * only difference is which model API is used to save the document back to Studio Pro.
 *
 * @param studioPro The Mendix Studio Pro API client
 * @param flowDocument The target microflow or nanoflow being formatted
 * @param newCoordinates The Map of coordinates generated by the DAG algorithm
 * @param kind Which document is being formatted, used for the model API and the message
 */
export async function applyFlowLayout(
    studioPro: any,
    flowDocument: any,
    newCoordinates: Map<string, { x: number, y: number }>,
    kind: "microflow" | "nanoflow"
): Promise<void> {

    try {
        // 1. Iterate through all objects in the document
        const objects = flowDocument.objectCollection?.objects || [];

        objects.forEach((obj: any) => {
            // Retrieve the calculated coordinates for this specific object ID
            const newPos = newCoordinates.get(obj.$ID);

            if (newPos) {
                // 2. Apply the new coordinates.
                obj.relativeMiddlePoint = { x: newPos.x, y: newPos.y };
            }
        });

        // 3. Reset flow line geometry so old curves/bends don't persist after moving nodes
        const flows = flowDocument.flows || [];
        flows.forEach((flow: any) => {
            const line = flow.line;
            if (line?.$Type === "Microflows$BezierCurve") {
                line.originControlVector = { width: 0, height: 0 };
                line.destinationControlVector = { width: 0, height: 0 };
            } else if (line?.$Type === "Microflows$OrthogonalPath") {
                line.segmentPositions = [];
            }
        });

        // 4. Save the modified document back to the Studio Pro UI
        const modelApi = kind === "nanoflow"
            ? studioPro.app.model.nanoflows
            : studioPro.app.model.microflows;
        await modelApi.save(flowDocument);

        const label = kind === "nanoflow" ? "Nanoflow" : "Microflow";
        studioPro.ui.messageBoxes.show(
            "info",
            `${label} formatted!`,
            "Press Ctrl+S to save the changes to disk."
        );

    } catch (error: any) {
        throw new Error(`Failed to apply ${kind} layout: ${error}`);
    }
}